version: '3.7'

services:
    app:
        build:
          context: ./app
          dockerfile: dockerfile.prod
        command: gunicorn nature_lib.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - ./app/:/usr/src/app/
            - static_volume:/usr/src/app/staticfiles
        expose:
            - 8000
        env_file: .env
        depends_on:
            - db
    db:
        image: postgres:11.4-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file: .env.db
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/usr/src/app/staticfiles
        ports:
            - 1337:80
        depends_on:
            - app
volumes:
  postgres_data:
  static_volume:
